[package]
authors = ["Russell McClellan <russell.mcclellan@gmail.com>"]
name = "gbatest"
version = "0.1.0"

[dependencies.gba-rt]
path = "../gba-rt"

[dependencies.gba-bios]
path = "../gba-bios"

[dependencies.gba-hw]
path = "../gba-hw"