[package]
authors = ["Russell McClellan <russell.mcclellan@gmail.com>"]
name = "gba-register-generator"
version = "0.1.0"

[dependencies]
derive_builder = "0.4.4"
error-chain = "0.10.0"
quote = "0.3.15"
syn = "0.11.10"
